# Generated by Django 5.2 on 2026-04-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('objects_data', models.JSONField()),
                ('operation', models.CharField(max_length=255)),
                ('activity_created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_updated_at', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('trk_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trk_file_path', models.TextField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('project_status', models.CharField(default='inprogress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='OperationSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('before_state', models.JSONField()),
                ('after_state', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='video.activitylog'
                    ),
                ),
            ],
            options={
                'db_table': 'operation_snapshot',
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.project'),
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_no', models.IntegerField()),
                ('frame_timestamp', models.FloatField(blank=True, null=True)),
                ('trk_timestamp', models.FloatField(blank=True, null=True)),
                (
                    'project_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='video.project'),
                ),
            ],
            options={
                'db_table': 'video_frame',
            },
        ),
        migrations.CreateModel(
            name='FrameObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('confidence', models.JSONField(blank=True, null=True)),
                ('tag', models.JSONField(blank=True, null=True)),
                ('timestamp', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'frame',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='frame_objects', to='video.videoframe'
                    ),
                ),
            ],
            options={
                'db_table': 'frame_object',
            },
        ),
        migrations.CreateModel(
            name='ObjectTrack',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('object_status', models.IntegerField(default=1)),
                ('operation_note', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'project_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='object_tracks', to='video.project'
                    ),
                ),
            ],
            options={
                'db_table': 'object_track',
                'indexes': [
                    models.Index(fields=['project_id', 'object_id'], name='object_trac_project_73969f_idx'),
                    models.Index(fields=['project_id', 'object_status'], name='object_trac_project_26101f_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project_id', 'is_applied'], name='activity_lo_project_48a2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='videoframe',
            index=models.Index(fields=['project_id', 'frame_no'], name='video_frame_project_f8e2da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoframe',
            unique_together={('project_id', 'frame_no')},
        ),
        migrations.AddIndex(
            model_name='frameobject',
            index=models.Index(fields=['frame', 'object_id'], name='frame_objec_frame_i_321615_idx'),
        ),
        migrations.AddIndex(
            model_name='frameobject',
            index=models.Index(fields=['object_id'], name='frame_objec_object__a33112_idx'),
        ),
    ]
