# Generated by Django 5.2 on 2026-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='frameobject',
            name='frame_objec_frame_i_321615_idx',
        ),
        migrations.AddIndex(
            model_name='frameobject',
            index=models.Index(fields=['frame', 'object_id', 'is_active'], name='frame_objec_frame_i_166137_idx'),
        ),
    ]
