# Generated by Django 5.2 on 2026-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_frameobject_frame_objec_frame_i_321615_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='frameobject',
            name='frame_objec_frame_i_166137_idx',
        ),
        migrations.AddIndex(
            model_name='frameobject',
            index=models.Index(fields=['frame', 'is_active'], name='frame_objec_frame_i_2ca241_idx'),
        ),
    ]
