# Generated by Django 5.2 on 2026-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_frameobject_frame_objec_frame_i_166137_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='frameobject',
            index=models.Index(fields=['is_active', 'frame', 'object_id'], name='frame_objec_is_acti_94e32b_idx'),
        ),
    ]
