# Generated by Django 5.2 on 2026-05-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_frameobject_frame_objec_is_acti_94e32b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameConfusion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame_no', models.IntegerField()),
                ('next_frame_no', models.IntegerField()),
                ('current_object_id', models.IntegerField()),
                ('best_match_object_id', models.IntegerField(blank=True, null=True)),
                ('second_match_object_id', models.IntegerField(blank=True, null=True)),
                ('uncertainty', models.FloatField()),
                ('is_forward', models.BooleanField(default=True)),
                ('best_match_cost', models.FloatField(blank=True, null=True)),
                ('second_match_cost', models.FloatField(blank=True, null=True)),
                ('nearby_object_count', models.IntegerField(default=0)),
                ('confusion_score', models.FloatField(blank=True, null=True)),
                ('is_crowded', models.BooleanField(default=False)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='frame_confusions', to='video.project'
                    ),
                ),
            ],
            options={
                'db_table': 'frame_confusion',
                'indexes': [
                    models.Index(fields=['project', 'frame_no'], name='frame_confu_project_ab657d_idx'),
                    models.Index(fields=['project', 'uncertainty'], name='frame_confu_project_fabae7_idx'),
                    models.Index(fields=['project', 'current_object_id'], name='frame_confu_project_cf8c25_idx'),
                    models.Index(fields=['project', 'best_match_object_id'], name='frame_confu_project_bdde5a_idx'),
                    models.Index(fields=['project', 'frame_no', 'uncertainty'], name='frame_confu_project_5ca028_idx'),
                    models.Index(fields=['project', 'is_crowded'], name='frame_confu_project_368fd2_idx'),
                    models.Index(fields=['project', 'event_type'], name='frame_confu_project_059f12_idx'),
                    models.Index(fields=['project', 'confusion_score'], name='frame_confu_project_4149a3_idx'),
                    models.Index(fields=['project', 'is_crowded', 'confusion_score'], name='frame_confu_project_a92089_idx'),
                ],
            },
        ),
    ]
