# Generated by Django 5.2 on 2026-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_frameconfusion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_fabae7_idx',
        ),
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_bdde5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_5ca028_idx',
        ),
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_368fd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_4149a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='frameconfusion',
            name='frame_confu_project_a92089_idx',
        ),
        migrations.AddIndex(
            model_name='frameconfusion',
            index=models.Index(fields=['project', '-confusion_score'], name='frame_confu_project_8c632e_idx'),
        ),
    ]
