# Generated by Django 5.2 on 2026-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_remove_frameconfusion_frame_confu_project_fabae7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameobject',
            name='is_interpolated',
            field=models.BooleanField(default=False),
        ),
    ]
