# Generated by Django 5.2 on 2026-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_frameobject_is_interpolated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confusion_status',
            field=models.CharField(default='COMPLETED', max_length=20),
        ),
    ]
