# Generated by Django 5.2 on 2026-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_project_confusion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameconfusion',
            name='nearby_object_ids',
            field=models.JSONField(
                blank=True, default=list, help_text='List of object IDs that are within the crowd radius', null=True
            ),
        ),
    ]
