# Generated by Django 5.2 on 2026-06-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_frameconfusion_nearby_object_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLinkingSuggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_end_frame', models.IntegerField()),
                ('target_start_frame', models.IntegerField()),
                ('distance', models.FloatField()),
                ('match_score', models.FloatField()),
                ('is_best_match', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('confusion_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='linking_suggestions', to='video.project'
                    ),
                ),
                (
                    'source_track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='as_source', to='video.objecttrack'
                    ),
                ),
                (
                    'target_track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='as_target', to='video.objecttrack'
                    ),
                ),
            ],
            options={
                'db_table': 'object_linking_suggestion',
                'indexes': [
                    models.Index(fields=['project', 'source_track'], name='object_link_project_a27ea1_idx'),
                    models.Index(fields=['project', 'target_track'], name='object_link_project_c53851_idx'),
                    models.Index(fields=['source_track', 'is_best_match'], name='object_link_source__250b2b_idx'),
                ],
            },
        ),
    ]
