# Generated by Django 5.2 on 2026-06-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_objectlinkingsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skeleton_graph',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
