# Generated by Django 5.2 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_project_skeleton_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trk_storage_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_storage_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
